app/applicants/urls.py
from django.urls import path

from . import views

app_name = 'applicants'


urlpatterns = [
    path('create', views.ApplicantCreateView.as_view(), name='applicant-create'),
    path('detail/<int:pk>', views.ApplicantDetailView.as_view(), name='applicant-detail'),
]

app/applications/urls.py
from django.urls import path

from . import views

app_name = "applications"

urlpatterns = [
    path("", views.ApplicationListView.as_view(), name="application-list"),
]

app/cf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mixin.assets import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("applicants/", include("applicants.urls", namespace="applicants")),
    path("applications/", include("applications.urls", namespace="applications")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport"
    content="width=device-width, initial-scale=1">

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.js"
    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>

  <!-- Bootstrap CSS -->
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous">

  <link rel="stylesheet"
    href="{% static 'css/main.css'%}">

  <title>

    {% block head_title %}

    {% endblock head_title %}
    - Crown Lands
  </title>
</head>

<body>
  {% include 'header.html' %}

  {% block content %}

  {% endblock content %}


  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"
    aria-label="navbar example">
    <div class="container-xl">
        <a class="navbar-brand fs-1"
            href="/">Crown Lands</a>
        <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarsExample07XL"
            aria-controls="navbarsExample07XL"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse"
            id="navbarsExample07XL">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link"
                        aria-current="page"
                        href="{% url 'applications:application-list' %}">Applications</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link"
                        href="#">Link</a>
                </li> -->


            </ul>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                        href="#"
                        id="dropdown07XL"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">{{user}}</a>
                    <ul class="dropdown-menu"
                        aria-labelledby="dropdown07XL">
                        <li><a class="dropdown-item"
                                href="#">Profile</a></li>
                        <li><a class="dropdown-item"
                                href="#">Change E-mail</a></li>
                        <hr>
                        <li><a class="dropdown-item"
                                href="#">Sign out</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
            <!-- <form>
                <input class="form-control"
                    type="text"
                    placeholder="Search"
                    aria-label="Search">
            </form> -->
        </div>
    </div>
</nav>

app/templates/index.html
{% extends 'base.html' %}


{% block head_title %}
Home
{% endblock head_title %}


{% block content %}
<div class="container my-5">
    <h1 class="fs-1">Home</h1>
    <hr>
    <a class="text-decoration-none text-light"
        href="{% url 'applicants:applicant-create' %}">
        <div class="card bg-dark"
            style="width: 22rem;">
            <h5 class="card-header">Start an application process</h5>
            <div class="card-body">
                <p class="card-text">Record Application inform</p>

            </div>
        </div>
    </a>
</div>
{% endblock content %}